name: Secure Pipeline Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/config
          
    
          
      - name: Build Application
        run: |
          npm install 
          
          npm run build

        
          
      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r build ${{ secrets.EC2_INSTANCE_USER }}@${{ secrets.EC2_INSTANCE_IP }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_INSTANCE_USER }}@${{ secrets.EC2_INSTANCE_IP }} 'cd /home/ubuntu  && pm2 delete react-build && pm2 serve build/ 3000 --name "react-build" --spa && exit'
